### ISSUE TITLE
How does one download this custom client for android?

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [blahblahbloopster/mindustry-client#18]
Plz tell me

**Comment by buthed010203** [comment]
Currently, the client doesn't work on android but foo is looking into making that possible.
Not to mention that this version of the client was for v5.

**Comment by USMP-lancer** [comment]
This the man who has a fork of the wifi brute hack

**Comment by USMP-lancer** [comment]
Hecc

**Comment by XxsuperdeadlysniperxX** [comment]
Yup i has a issue on the wifi brute hack

**Comment by XxsuperdeadlysniperxX** [comment]
@bvcbvc and the issue has not been looked at in 2 months lol

**Comment by USMP-lancer** [comment]
its kinda sus is all im saying

**Comment by XxsuperdeadlysniperxX** [comment]
In that issue i was telling thedevf that his site is down and i wouldn't gave been able to run it if the requirements use a computer plus theres actual practical reasons to use a brute forcer as this is considered a pen test tool

**Comment by XxsuperdeadlysniperxX** [comment]
Pen (penetration)

**Comment by XxsuperdeadlysniperxX** [comment]
@bvcbvc but like any penetration test tool it has good uses and malicious uses
The following is only two examples of the many uses the tool has:
The good:
#1 Testing to see how secure your wifi settings actually are
#2 seeing how strong the wifi's firewall is
The bad:
#1 stealing passwords to use wifi
#2 ddosing the the wifi
#3 other attacks you must look up cuz they have a complicated nane and this issues topic went way off track

**Comment by XxsuperdeadlysniperxX** [comment]
I would advise against tapping the numbers as the links are not intended cuslz they lead to closed issues

**Comment by USMP-lancer** [comment]
1. numbered
2. list

**Comment by XxsuperdeadlysniperxX** [comment]
Yup i use the number sign as thats a habit from high school
